### ISSUE TITLE
Edits needed

### ISSUE THREAD

**Issue by akshitadixit** [GDSC-IIIT-Kalyani/todo-tracker#1]
* Add setting up and installation instructions for beginner level understanding
* Add easier and more elaborate usage instructions
* Structure the README properly
* Add issues ranging from beginner to medium-high level
* Add license
* The contributing.md file doesn't contain any contributing guidelines at all

**Comment by TathagataRoy1278** [comment]
Working on them

**Comment by TathagataRoy1278** [comment]
Except the Windows integration for beginners everything has been managed. For the later an issue is being opened.
