### ISSUE TITLE
Change the size of the opening Window.

### ISSUE THREAD

**Issue by TathagataRoy1278** [GDSC-IIIT-Kalyani/todo-tracker#4]
The window that opens as is, is too small. Make it bigger.

**Comment by r-guy** [comment]
@TathagataRoy1278 I want to work on this issue.

**Comment by TathagataRoy1278** [comment]
@Apurba-Nath-cpu I already fixed the issue with ubunutu on PR #12 , check with @matrixbot123 as he is the one working on windows
