### ISSUE TITLE
Add a config file for global variables.

### ISSUE THREAD

**Issue by TathagataRoy1278** [GDSC-IIIT-Kalyani/todo-tracker#5]
Make a config file like xml/yaml to implement global variables like the location where the task information is stored. That is [here](https://github.com/GDSC-IIIT-Kalyani/todo-tracker/blob/master/commands.py#L7) . This is just an example, add more if possible.

**Comment by r-guy** [comment]
@TathagataRoy1278 Can I work on this issue ?

**Comment by TathagataRoy1278** [comment]
@Apurba-Nath-cpu I already fixed the issue with config.py in PR #12
