### ISSUE TITLE
Add a batch script and keyboard binding instructions for Windows.

### ISSUE THREAD

**Issue by TathagataRoy1278** [GDSC-IIIT-Kalyani/todo-tracker#8]
Add a batch script that runs the program and modify README.md with how to add keyboard shortcuts instructions for Windows.

**Comment by matrixbot123** [comment]
you mean similar to what has been done in run.sh just done in batch file in windows with keybinding?

**Comment by TathagataRoy1278** [comment]
Precisely

**Comment by venkat-619** [comment]
hello tathagatha i can work on this issue

**Comment by TathagataRoy1278** [comment]
yeah please

**Comment by TathagataRoy1278** [comment]
Solved by @venkat-619 in #19

**Comment by TathagataRoy1278** [comment]
Add environment variables in config.py for windows from `run_todo.bat`.

If you clone this repo as is, and run `run_todo.bat` in windows, it will throw an error saying that config.py is missing. Make a batch file like `install.sh` for windows to set variables in config.py

@venkat-619

**Comment by venkat-619** [comment]
ok . @TathagataRoy1278
