### ISSUE TITLE
run.sh is not configured for different Terminal Emulator

### ISSUE THREAD

**Issue by matrixbot123** [GDSC-IIIT-Kalyani/todo-tracker#9]
Different Linux distros may have different Terminal Emulator (eg. qterminal and gnome) and the run.sh only works for gnome. So is gnome requirement or should it be optimal to run on emulator.

**Comment by TathagataRoy1278** [comment]
Hey @matrixbot123 check this out https://askubuntu.com/questions/46627/how-can-i-make-a-script-that-opens-terminal-windows-and-executes-commands-in-the

**Comment by matrixbot123** [comment]
okay thanks, @TathagataRoy1278  I was looking to organize things

**Comment by TathagataRoy1278** [comment]
yessir
